version: "3.9"

services:
  app:
    build: ./app
    container_name: deolho-app
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    stdin_open: true
    tty: true
    depends_on:
      - api

  api:
    build: ./api
    container_name: deolho-api
    volumes:
      - ./api:/api
      - /api/node_modules
    ports:
      - "4000:4000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/deolho
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    container_name: deolho-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
